version: '3'
services:

  database:
    container_name: stocks-db
    image: postgres
#    network_mode: host
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
